### PR TITLE
vagrant

### LINKED ISSUE #4: cannot get it running
My brain is square and I could not get this masterpiece to run.

Because my computer said some modules (I think the crypto one and some others) are deprecated or smth a couple weeks ago when I spent about 45 minutes racking my brain and googling nonsense.

So uh, can you host it somewhere like replit or something?

### PR DESCRIPTION
**Pull request by liimee**
`vagrant up` should work

*should* fix #4

### CODE REVIEW

**Comment by liimee** [comment]
@electogenius did this work?

**Comment by Electogenius** [comment]
Well I remember typing out what happened but it seems I forgot to post and it somehow wasn't saved.

No, it didn't work because none of the 'providers' vagrant uses seem to be supported.

Virtualbox doesn't work, docker seems to be installed but the docker command gives a permission denied error which also occurs when I run `vagrant up --provider=docker`

I think smth is wrong with my docker thingy (also I think my shell is trying to run a folder when I run `docker`)

Oh wait I gave the folder execute permission and it runs.

Vagrant still gives an obnoxiously long and unreadable permission denied error.

I'll try to fix it or maybe I can use docker instead of vagrant?

**Comment by liimee** [comment]
>  I'll try to fix it or maybe I can use docker instead of vagrant?

that means I should add a dockerfile right?

**Comment by liimee** [comment]
```
sudo docker build -t another-nothing .
sudo docker run -p=3000:3000 another-nothing
```

should work hopefully?

btw tbh I prefer vagrant but ok

**Comment by Electogenius** [comment]
OH MY GODDNESS FINALLY!

DOCKER IS MAGIC AAAAAA

well technically I know what the UI looks like by just http serving the repo but now it actually functions

Lol this is really cool

**Comment by liimee** [comment]
> Lol this is really cool

docker is
nothing isn't
oh hmmos is cool too

merge ig?

**Comment by Electogenius** [comment]
>docker is
nothing isn't

Exactly. Only docker is magic. Nothing isn't magic, it's sorcery.

Sure then, you can merge

BTW I tested it on my iPad, everything works except the apps, which just show 'no'

**Comment by liimee** [comment]
> BTW I tested it on my iPad, everything works except the apps, which just show 'no'

oh right
I think it's the regex and HHH variable

**Comment by liimee** [comment]
> BTW I tested it on my iPad, everything works except the apps, which just show 'no'

this is fixed in eefb592889ad6b65d73ab190a951a2b4d5d7c07e

**Pull request merged**
